name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # To push to gh-pages branch
      pages: write # To deploy to Pages
      id-token: write # To enable OIDC for secure deployment (optional but recommended)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your preferred Node.js version
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build SvelteKit app
        run: npm run build
        env:
          # If your GitHub repository is, for example, `your-username/your-repo-name`,
          # and you're deploying to `your-username.github.io/your-repo-name/`,
          # you need to set the base path.
          # SvelteKit uses `paths.base` in svelte.config.js, which can be set via an environment variable.
          # If deploying to `your-username.github.io` (a root domain for the user/org),
          # then this base path is not needed (empty string).
          # Replace `your-repo-name` with your actual repository name if deploying to a subpath.
          BASE_PATH: '/${{ github.event.repository.name }}' # Or '' if deploying to root

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build # Default build output directory for adapter-static

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
